name: "ATP Sync and Backup"
description: "Sync files and backup from an upstream repo, with env and replace rules."
inputs:
  env-file:
    description: "Path to the repo.env config file"
    required: false
    default: repo.env
runs:
  using: "composite"
  steps:
    - name: Load env with priority (secrets/env > repo.env)
      shell: bash
      run: |
        bash "${{ github.action_path }}/env_priority.sh" "${{ inputs.env-file }}"

    - name: Debug env after loading
      shell: bash
      run: |
        echo "BACKUP_BRANCH='$BACKUP_BRANCH'"
        echo "UPSTREAM_URL='$UPSTREAM_URL'"
        env | grep -E 'BACKUP_BRANCH|UPSTREAM_URL'
        
    - name: Main backup/sync logic
      shell: bash
      run: |
        bash "${{ github.action_path }}/sync_and_replace.sh"