name: "Sync and Backup Workflow"
description: "Sync code từ upstream, backup commit, replace keyword, ưu tiên secrets > section-style repo.env"
inputs:
  env-file:
    description: "Path đến file env, mặc định là repo.env"
    required: false
    default: "repo.env"
runs:
  using: "composite"
  steps:
    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/env_priority.sh"
        chmod +x "${{ github.action_path }}/sync_and_replace.sh"

    - name: Load env variables from secrets or repo.env
      shell: bash
      run: |
        "${{ github.action_path }}/env_priority.sh" "${{ inputs.env-file }}"

    - name: Run sync and replace logic
      shell: bash
      run: |
        "${{ github.action_path }}/sync_and_replace.sh"